#ifndef __INTEL_XED_OPCODES__HPP
#define __INTEL_XED_OPCODES__HPP

#define INTEL_XED_OPCODES(F)                    \
      F(AAA)                                    \
      F(AAD)                                    \
      F(AAM)                                    \
      F(AAS)                                    \
      F(ADC)                                    \
      F(ADCX)                                   \
      F(ADD)                                    \
      F(ADDPD)                                  \
      F(ADDPS)                                  \
      F(ADDSD)                                  \
      F(ADDSS)                                  \
      F(ADDSUBPD)                               \
      F(ADDSUBPS)                               \
      F(ADOX)                                   \
      F(AESDEC)                                 \
      F(AESDECLAST)                             \
      F(AESENC)                                 \
      F(AESENCLAST)                             \
      F(AESIMC)                                 \
      F(AESKEYGENASSIST)                        \
      F(AND)                                    \
      F(ANDN)                                   \
      F(ANDNPD)                                 \
      F(ANDNPS)                                 \
      F(ANDPD)                                  \
      F(ANDPS)                                  \
      F(ARPL)                                   \
      F(BEXTR)                                  \
      F(BEXTR_XOP)                              \
      F(BLCFILL)                                \
      F(BLCI)                                   \
      F(BLCIC)                                  \
      F(BLCMSK)                                 \
      F(BLCS)                                   \
      F(BLENDPD)                                \
      F(BLENDPS)                                \
      F(BLENDVPD)                               \
      F(BLENDVPS)                               \
      F(BLSFILL)                                \
      F(BLSI)                                   \
      F(BLSIC)                                  \
      F(BLSMSK)                                 \
      F(BLSR)                                   \
      F(BOUND)                                  \
      F(BSF)                                    \
      F(BSR)                                    \
      F(BSWAP)                                  \
      F(BT)                                     \
      F(BTC)                                    \
      F(BTR)                                    \
      F(BTS)                                    \
      F(BZHI)                                   \
      F(CALL_FAR)                               \
      F(CALL_NEAR)                              \
      F(CBW)                                    \
      F(CDQ)                                    \
      F(CDQE)                                   \
      F(CLC)                                    \
      F(CLD)                                    \
      F(CLFLUSH)                                \
      F(CLGI)                                   \
      F(CLI)                                    \
      F(CLTS)                                   \
      F(CMC)                                    \
      F(CMOVB)                                  \
      F(CMOVBE)                                 \
      F(CMOVL)                                  \
      F(CMOVLE)                                 \
      F(CMOVNB)                                 \
      F(CMOVNBE)                                \
      F(CMOVNL)                                 \
      F(CMOVNLE)                                \
      F(CMOVNO)                                 \
      F(CMOVNP)                                 \
      F(CMOVNS)                                 \
      F(CMOVNZ)                                 \
      F(CMOVO)                                  \
      F(CMOVP)                                  \
      F(CMOVS)                                  \
      F(CMOVZ)                                  \
      F(CMP)                                    \
      F(CMPPD)                                  \
      F(CMPPS)                                  \
      F(CMPSB)                                  \
      F(CMPSD)                                  \
      F(CMPSD_XMM)                              \
      F(CMPSQ)                                  \
      F(CMPSS)                                  \
      F(CMPSW)                                  \
      F(CMPXCHG)                                \
      F(CMPXCHG16B)                             \
      F(CMPXCHG8B)                              \
      F(COMISD)                                 \
      F(COMISS)                                 \
      F(CPUID)                                  \
      F(CQO)                                    \
      F(CRC32)                                  \
      F(CVTDQ2PD)                               \
      F(CVTDQ2PS)                               \
      F(CVTPD2DQ)                               \
      F(CVTPD2PI)                               \
      F(CVTPD2PS)                               \
      F(CVTPI2PD)                               \
      F(CVTPI2PS)                               \
      F(CVTPS2DQ)                               \
      F(CVTPS2PD)                               \
      F(CVTPS2PI)                               \
      F(CVTSD2SI)                               \
      F(CVTSD2SS)                               \
      F(CVTSI2SD)                               \
      F(CVTSI2SS)                               \
      F(CVTSS2SD)                               \
      F(CVTSS2SI)                               \
      F(CVTTPD2DQ)                              \
      F(CVTTPD2PI)                              \
      F(CVTTPS2DQ)                              \
      F(CVTTPS2PI)                              \
      F(CVTTSD2SI)                              \
      F(CVTTSS2SI)                              \
      F(CWD)                                    \
      F(CWDE)                                   \
      F(DAA)                                    \
      F(DAS)                                    \
      F(DEC)                                    \
      F(DIV)                                    \
      F(DIVPD)                                  \
      F(DIVPS)                                  \
      F(DIVSD)                                  \
      F(DIVSS)                                  \
      F(DPPD)                                   \
      F(DPPS)                                   \
      F(EMMS)                                   \
      F(ENTER)                                  \
      F(EXTRACTPS)                              \
      F(EXTRQ)                                  \
      F(F2XM1)                                  \
      F(FABS)                                   \
      F(FADD)                                   \
      F(FADDP)                                  \
      F(FBLD)                                   \
      F(FBSTP)                                  \
      F(FCHS)                                   \
      F(FCMOVB)                                 \
      F(FCMOVBE)                                \
      F(FCMOVE)                                 \
      F(FCMOVNB)                                \
      F(FCMOVNBE)                               \
      F(FCMOVNE)                                \
      F(FCMOVNU)                                \
      F(FCMOVU)                                 \
      F(FCOM)                                   \
      F(FCOMI)                                  \
      F(FCOMIP)                                 \
      F(FCOMP)                                  \
      F(FCOMPP)                                 \
      F(FCOS)                                   \
      F(FDECSTP)                                \
      F(FDISI8087_NOP)                          \
      F(FDIV)                                   \
      F(FDIVP)                                  \
      F(FDIVR)                                  \
      F(FDIVRP)                                 \
      F(FEMMS)                                  \
      F(FENI8087_NOP)                           \
      F(FFREE)                                  \
      F(FFREEP)                                 \
      F(FIADD)                                  \
      F(FICOM)                                  \
      F(FICOMP)                                 \
      F(FIDIV)                                  \
      F(FIDIVR)                                 \
      F(FILD)                                   \
      F(FIMUL)                                  \
      F(FINCSTP)                                \
      F(FIST)                                   \
      F(FISTP)                                  \
      F(FISTTP)                                 \
      F(FISUB)                                  \
      F(FISUBR)                                 \
      F(FLD)                                    \
      F(FLD1)                                   \
      F(FLDCW)                                  \
      F(FLDENV)                                 \
      F(FLDL2E)                                 \
      F(FLDL2T)                                 \
      F(FLDLG2)                                 \
      F(FLDLN2)                                 \
      F(FLDPI)                                  \
      F(FLDZ)                                   \
      F(FMUL)                                   \
      F(FMULP)                                  \
      F(FNCLEX)                                 \
      F(FNINIT)                                 \
      F(FNOP)                                   \
      F(FNSAVE)                                 \
      F(FNSTCW)                                 \
      F(FNSTENV)                                \
      F(FNSTSW)                                 \
      F(FPATAN)                                 \
      F(FPREM)                                  \
      F(FPREM1)                                 \
      F(FPTAN)                                  \
      F(FRNDINT)                                \
      F(FRSTOR)                                 \
      F(FSCALE)                                 \
      F(FSETPM287_NOP)                          \
      F(FSIN)                                   \
      F(FSINCOS)                                \
      F(FSQRT)                                  \
      F(FST)                                    \
      F(FSTP)                                   \
      F(FSTPNCE)                                \
      F(FSUB)                                   \
      F(FSUBP)                                  \
      F(FSUBR)                                  \
      F(FSUBRP)                                 \
      F(FTST)                                   \
      F(FUCOM)                                  \
      F(FUCOMI)                                 \
      F(FUCOMIP)                                \
      F(FUCOMP)                                 \
      F(FUCOMPP)                                \
      F(FWAIT)                                  \
      F(FXAM)                                   \
      F(FXCH)                                   \
      F(FXRSTOR)                                \
      F(FXRSTOR64)                              \
      F(FXSAVE)                                 \
      F(FXSAVE64)                               \
      F(FXTRACT)                                \
      F(FYL2X)                                  \
      F(FYL2XP1)                                \
      F(GETSEC)                                 \
      F(HADDPD)                                 \
      F(HADDPS)                                 \
      F(HLT)                                    \
      F(HSUBPD)                                 \
      F(HSUBPS)                                 \
      F(IDIV)                                   \
      F(IMUL)                                   \
      F(IN)                                     \
      F(INC)                                    \
      F(INSB)                                   \
      F(INSD)                                   \
      F(INSERTPS)                               \
      F(INSERTQ)                                \
      F(INSW)                                   \
      F(INT)                                    \
      F(INT1)                                   \
      F(INT3)                                   \
      F(INTO)                                   \
      F(INVD)                                   \
      F(INVEPT)                                 \
      F(INVLPG)                                 \
      F(INVLPGA)                                \
      F(INVPCID)                                \
      F(INVVPID)                                \
      F(IRET)                                   \
      F(IRETD)                                  \
      F(IRETQ)                                  \
      F(JB)                                     \
      F(JBE)                                    \
      F(JL)                                     \
      F(JLE)                                    \
      F(JMP)                                    \
      F(JMP_FAR)                                \
      F(JNB)                                    \
      F(JNBE)                                   \
      F(JNL)                                    \
      F(JNLE)                                   \
      F(JNO)                                    \
      F(JNP)                                    \
      F(JNS)                                    \
      F(JNZ)                                    \
      F(JO)                                     \
      F(JP)                                     \
      F(JRCXZ)                                  \
      F(JS)                                     \
      F(JZ)                                     \
      F(LAHF)                                   \
      F(LAR)                                    \
      F(LDDQU)                                  \
      F(LDMXCSR)                                \
      F(LDS)                                    \
      F(LEA)                                    \
      F(LEAVE)                                  \
      F(LES)                                    \
      F(LFENCE)                                 \
      F(LFS)                                    \
      F(LGDT)                                   \
      F(LGS)                                    \
      F(LIDT)                                   \
      F(LLDT)                                   \
      F(LLWPCB)                                 \
      F(LMSW)                                   \
      F(LODSB)                                  \
      F(LODSD)                                  \
      F(LODSQ)                                  \
      F(LODSW)                                  \
      F(LOOP)                                   \
      F(LOOPE)                                  \
      F(LOOPNE)                                 \
      F(LSL)                                    \
      F(LSS)                                    \
      F(LTR)                                    \
      F(LWPINS)                                 \
      F(LWPVAL)                                 \
      F(LZCNT)                                  \
      F(MASKMOVDQU)                             \
      F(MASKMOVQ)                               \
      F(MAXPD)                                  \
      F(MAXPS)                                  \
      F(MAXSD)                                  \
      F(MAXSS)                                  \
      F(MFENCE)                                 \
      F(MINPD)                                  \
      F(MINPS)                                  \
      F(MINSD)                                  \
      F(MINSS)                                  \
      F(MONITOR)                                \
      F(MOV)                                    \
      F(MOVAPD)                                 \
      F(MOVAPS)                                 \
      F(MOVBE)                                  \
      F(MOVD)                                   \
      F(MOVDDUP)                                \
      F(MOVDQ2Q)                                \
      F(MOVDQA)                                 \
      F(MOVDQU)                                 \
      F(MOVHLPS)                                \
      F(MOVHPD)                                 \
      F(MOVHPS)                                 \
      F(MOVLHPS)                                \
      F(MOVLPD)                                 \
      F(MOVLPS)                                 \
      F(MOVMSKPD)                               \
      F(MOVMSKPS)                               \
      F(MOVNTDQ)                                \
      F(MOVNTDQA)                               \
      F(MOVNTI)                                 \
      F(MOVNTPD)                                \
      F(MOVNTPS)                                \
      F(MOVNTQ)                                 \
      F(MOVNTSD)                                \
      F(MOVNTSS)                                \
      F(MOVQ)                                   \
      F(MOVQ2DQ)                                \
      F(MOVSB)                                  \
      F(MOVSD)                                  \
      F(MOVSD_XMM)                              \
      F(MOVSHDUP)                               \
      F(MOVSLDUP)                               \
      F(MOVSQ)                                  \
      F(MOVSS)                                  \
      F(MOVSW)                                  \
      F(MOVSX)                                  \
      F(MOVSXD)                                 \
      F(MOVUPD)                                 \
      F(MOVUPS)                                 \
      F(MOVZX)                                  \
      F(MOV_CR)                                 \
      F(MOV_DR)                                 \
      F(MPSADBW)                                \
      F(MUL)                                    \
      F(MULPD)                                  \
      F(MULPS)                                  \
      F(MULSD)                                  \
      F(MULSS)                                  \
      F(MULX)                                   \
      F(MWAIT)                                  \
      F(NEG)                                    \
      F(NOP)                                    \
      F(NOP2)                                   \
      F(NOP3)                                   \
      F(NOP4)                                   \
      F(NOP5)                                   \
      F(NOP6)                                   \
      F(NOP7)                                   \
      F(NOP8)                                   \
      F(NOP9)                                   \
      F(NOT)                                    \
      F(OR)                                     \
      F(ORPD)                                   \
      F(ORPS)                                   \
      F(OUT)                                    \
      F(OUTSB)                                  \
      F(OUTSD)                                  \
      F(OUTSW)                                  \
      F(PABSB)                                  \
      F(PABSD)                                  \
      F(PABSW)                                  \
      F(PACKSSDW)                               \
      F(PACKSSWB)                               \
      F(PACKUSDW)                               \
      F(PACKUSWB)                               \
      F(PADDB)                                  \
      F(PADDD)                                  \
      F(PADDQ)                                  \
      F(PADDSB)                                 \
      F(PADDSW)                                 \
      F(PADDUSB)                                \
      F(PADDUSW)                                \
      F(PADDW)                                  \
      F(PALIGNR)                                \
      F(PAND)                                   \
      F(PANDN)                                  \
      F(PAUSE)                                  \
      F(PAVGB)                                  \
      F(PAVGUSB)                                \
      F(PAVGW)                                  \
      F(PBLENDVB)                               \
      F(PBLENDW)                                \
      F(PCLMULQDQ)                              \
      F(PCMPEQB)                                \
      F(PCMPEQD)                                \
      F(PCMPEQQ)                                \
      F(PCMPEQW)                                \
      F(PCMPESTRI)                              \
      F(PCMPESTRM)                              \
      F(PCMPGTB)                                \
      F(PCMPGTD)                                \
      F(PCMPGTQ)                                \
      F(PCMPGTW)                                \
      F(PCMPISTRI)                              \
      F(PCMPISTRM)                              \
      F(PDEP)                                   \
      F(PEXT)                                   \
      F(PEXTRB)                                 \
      F(PEXTRD)                                 \
      F(PEXTRQ)                                 \
      F(PEXTRW)                                 \
      F(PF2ID)                                  \
      F(PF2IW)                                  \
      F(PFACC)                                  \
      F(PFADD)                                  \
      F(PFCMPEQ)                                \
      F(PFCMPGE)                                \
      F(PFCMPGT)                                \
      F(PFCPIT1)                                \
      F(PFMAX)                                  \
      F(PFMIN)                                  \
      F(PFMUL)                                  \
      F(PFNACC)                                 \
      F(PFPNACC)                                \
      F(PFRCP)                                  \
      F(PFRCPIT2)                               \
      F(PFRSQIT1)                               \
      F(PFSQRT)                                 \
      F(PFSUB)                                  \
      F(PFSUBR)                                 \
      F(PHADDD)                                 \
      F(PHADDSW)                                \
      F(PHADDW)                                 \
      F(PHMINPOSUW)                             \
      F(PHSUBD)                                 \
      F(PHSUBSW)                                \
      F(PHSUBW)                                 \
      F(PI2FD)                                  \
      F(PI2FW)                                  \
      F(PINSRB)                                 \
      F(PINSRD)                                 \
      F(PINSRQ)                                 \
      F(PINSRW)                                 \
      F(PMADDUBSW)                              \
      F(PMADDWD)                                \
      F(PMAXSB)                                 \
      F(PMAXSD)                                 \
      F(PMAXSW)                                 \
      F(PMAXUB)                                 \
      F(PMAXUD)                                 \
      F(PMAXUW)                                 \
      F(PMINSB)                                 \
      F(PMINSD)                                 \
      F(PMINSW)                                 \
      F(PMINUB)                                 \
      F(PMINUD)                                 \
      F(PMINUW)                                 \
      F(PMOVMSKB)                               \
      F(PMOVSXBD)                               \
      F(PMOVSXBQ)                               \
      F(PMOVSXBW)                               \
      F(PMOVSXDQ)                               \
      F(PMOVSXWD)                               \
      F(PMOVSXWQ)                               \
      F(PMOVZXBD)                               \
      F(PMOVZXBQ)                               \
      F(PMOVZXBW)                               \
      F(PMOVZXDQ)                               \
      F(PMOVZXWD)                               \
      F(PMOVZXWQ)                               \
      F(PMULDQ)                                 \
      F(PMULHRSW)                               \
      F(PMULHRW)                                \
      F(PMULHUW)                                \
      F(PMULHW)                                 \
      F(PMULLD)                                 \
      F(PMULLW)                                 \
      F(PMULUDQ)                                \
      F(POP)                                    \
      F(POPA)                                   \
      F(POPAD)                                  \
      F(POPCNT)                                 \
      F(POPF)                                   \
      F(POPFD)                                  \
      F(POPFQ)                                  \
      F(POR)                                    \
      F(PREFETCHNTA)                            \
      F(PREFETCHT0)                             \
      F(PREFETCHT1)                             \
      F(PREFETCHT2)                             \
      F(PREFETCHW)                              \
      F(PREFETCH_EXCLUSIVE)                     \
      F(PREFETCH_RESERVED)                      \
      F(PSADBW)                                 \
      F(PSHUFB)                                 \
      F(PSHUFD)                                 \
      F(PSHUFHW)                                \
      F(PSHUFLW)                                \
      F(PSHUFW)                                 \
      F(PSIGNB)                                 \
      F(PSIGND)                                 \
      F(PSIGNW)                                 \
      F(PSLLD)                                  \
      F(PSLLDQ)                                 \
      F(PSLLQ)                                  \
      F(PSLLW)                                  \
      F(PSRAD)                                  \
      F(PSRAW)                                  \
      F(PSRLD)                                  \
      F(PSRLDQ)                                 \
      F(PSRLQ)                                  \
      F(PSRLW)                                  \
      F(PSUBB)                                  \
      F(PSUBD)                                  \
      F(PSUBQ)                                  \
      F(PSUBSB)                                 \
      F(PSUBSW)                                 \
      F(PSUBUSB)                                \
      F(PSUBUSW)                                \
      F(PSUBW)                                  \
      F(PSWAPD)                                 \
      F(PTEST)                                  \
      F(PUNPCKHBW)                              \
      F(PUNPCKHDQ)                              \
      F(PUNPCKHQDQ)                             \
      F(PUNPCKHWD)                              \
      F(PUNPCKLBW)                              \
      F(PUNPCKLDQ)                              \
      F(PUNPCKLQDQ)                             \
      F(PUNPCKLWD)                              \
      F(PUSH)                                   \
      F(PUSHA)                                  \
      F(PUSHAD)                                 \
      F(PUSHF)                                  \
      F(PUSHFD)                                 \
      F(PUSHFQ)                                 \
      F(PXOR)                                   \
      F(RCL)                                    \
      F(RCPPS)                                  \
      F(RCPSS)                                  \
      F(RCR)                                    \
      F(RDFSBASE)                               \
      F(RDGSBASE)                               \
      F(RDMSR)                                  \
      F(RDPMC)                                  \
      F(RDRAND)                                 \
      F(RDSEED)                                 \
      F(RDTSC)                                  \
      F(RDTSCP)                                 \
      F(RET_FAR)                                \
      F(RET_NEAR)                               \
      F(ROL)                                    \
      F(ROR)                                    \
      F(RORX)                                   \
      F(ROUNDPD)                                \
      F(ROUNDPS)                                \
      F(ROUNDSD)                                \
      F(ROUNDSS)                                \
      F(RSM)                                    \
      F(RSQRTPS)                                \
      F(RSQRTSS)                                \
      F(SAHF)                                   \
      F(SALC)                                   \
      F(SAR)                                    \
      F(SARX)                                   \
      F(SBB)                                    \
      F(SCASB)                                  \
      F(SCASD)                                  \
      F(SCASQ)                                  \
      F(SCASW)                                  \
      F(SETB)                                   \
      F(SETBE)                                  \
      F(SETL)                                   \
      F(SETLE)                                  \
      F(SETNB)                                  \
      F(SETNBE)                                 \
      F(SETNL)                                  \
      F(SETNLE)                                 \
      F(SETNO)                                  \
      F(SETNP)                                  \
      F(SETNS)                                  \
      F(SETNZ)                                  \
      F(SETO)                                   \
      F(SETP)                                   \
      F(SETS)                                   \
      F(SETZ)                                   \
      F(SFENCE)                                 \
      F(SGDT)                                   \
      F(SHL)                                    \
      F(SHLD)                                   \
      F(SHLX)                                   \
      F(SHR)                                    \
      F(SHRD)                                   \
      F(SHRX)                                   \
      F(SHUFPD)                                 \
      F(SHUFPS)                                 \
      F(SIDT)                                   \
      F(SKINIT)                                 \
      F(SLDT)                                   \
      F(SLWPCB)                                 \
      F(SMSW)                                   \
      F(SQRTPD)                                 \
      F(SQRTPS)                                 \
      F(SQRTSD)                                 \
      F(SQRTSS)                                 \
      F(STC)                                    \
      F(STD)                                    \
      F(STGI)                                   \
      F(STI)                                    \
      F(STMXCSR)                                \
      F(STOSB)                                  \
      F(STOSD)                                  \
      F(STOSQ)                                  \
      F(STOSW)                                  \
      F(STR)                                    \
      F(SUB)                                    \
      F(SUBPD)                                  \
      F(SUBPS)                                  \
      F(SUBSD)                                  \
      F(SUBSS)                                  \
      F(SWAPGS)                                 \
      F(SYSCALL)                                \
      F(SYSCALL_AMD)                            \
      F(SYSENTER)                               \
      F(SYSEXIT)                                \
      F(SYSRET)                                 \
      F(SYSRET_AMD)                             \
      F(T1MSKC)                                 \
      F(TEST)                                   \
      F(TZCNT)                                  \
      F(TZMSK)                                  \
      F(UCOMISD)                                \
      F(UCOMISS)                                \
      F(UD2)                                    \
      F(UNPCKHPD)                               \
      F(UNPCKHPS)                               \
      F(UNPCKLPD)                               \
      F(UNPCKLPS)                               \
      F(VADDPD)                                 \
      F(VADDPS)                                 \
      F(VADDSD)                                 \
      F(VADDSS)                                 \
      F(VADDSUBPD)                              \
      F(VADDSUBPS)                              \
      F(VAESDEC)                                \
      F(VAESDECLAST)                            \
      F(VAESENC)                                \
      F(VAESENCLAST)                            \
      F(VAESIMC)                                \
      F(VAESKEYGENASSIST)                       \
      F(VANDNPD)                                \
      F(VANDNPS)                                \
      F(VANDPD)                                 \
      F(VANDPS)                                 \
      F(VBLENDPD)                               \
      F(VBLENDPS)                               \
      F(VBLENDVPD)                              \
      F(VBLENDVPS)                              \
      F(VBROADCASTF128)                         \
      F(VBROADCASTI128)                         \
      F(VBROADCASTSD)                           \
      F(VBROADCASTSS)                           \
      F(VCMPPD)                                 \
      F(VCMPPS)                                 \
      F(VCMPSD)                                 \
      F(VCMPSS)                                 \
      F(VCOMISD)                                \
      F(VCOMISS)                                \
      F(VCVTDQ2PD)                              \
      F(VCVTDQ2PS)                              \
      F(VCVTPD2DQ)                              \
      F(VCVTPD2PS)                              \
      F(VCVTPH2PS)                              \
      F(VCVTPS2DQ)                              \
      F(VCVTPS2PD)                              \
      F(VCVTPS2PH)                              \
      F(VCVTSD2SI)                              \
      F(VCVTSD2SS)                              \
      F(VCVTSI2SD)                              \
      F(VCVTSI2SS)                              \
      F(VCVTSS2SD)                              \
      F(VCVTSS2SI)                              \
      F(VCVTTPD2DQ)                             \
      F(VCVTTPS2DQ)                             \
      F(VCVTTSD2SI)                             \
      F(VCVTTSS2SI)                             \
      F(VDIVPD)                                 \
      F(VDIVPS)                                 \
      F(VDIVSD)                                 \
      F(VDIVSS)                                 \
      F(VDPPD)                                  \
      F(VDPPS)                                  \
      F(VERR)                                   \
      F(VERW)                                   \
      F(VEXTRACTF128)                           \
      F(VEXTRACTI128)                           \
      F(VEXTRACTPS)                             \
      F(VFMADD132PD)                            \
      F(VFMADD132PS)                            \
      F(VFMADD132SD)                            \
      F(VFMADD132SS)                            \
      F(VFMADD213PD)                            \
      F(VFMADD213PS)                            \
      F(VFMADD213SD)                            \
      F(VFMADD213SS)                            \
      F(VFMADD231PD)                            \
      F(VFMADD231PS)                            \
      F(VFMADD231SD)                            \
      F(VFMADD231SS)                            \
      F(VFMADDPD)                               \
      F(VFMADDPS)                               \
      F(VFMADDSD)                               \
      F(VFMADDSS)                               \
      F(VFMADDSUB132PD)                         \
      F(VFMADDSUB132PS)                         \
      F(VFMADDSUB213PD)                         \
      F(VFMADDSUB213PS)                         \
      F(VFMADDSUB231PD)                         \
      F(VFMADDSUB231PS)                         \
      F(VFMADDSUBPD)                            \
      F(VFMADDSUBPS)                            \
      F(VFMSUB132PD)                            \
      F(VFMSUB132PS)                            \
      F(VFMSUB132SD)                            \
      F(VFMSUB132SS)                            \
      F(VFMSUB213PD)                            \
      F(VFMSUB213PS)                            \
      F(VFMSUB213SD)                            \
      F(VFMSUB213SS)                            \
      F(VFMSUB231PD)                            \
      F(VFMSUB231PS)                            \
      F(VFMSUB231SD)                            \
      F(VFMSUB231SS)                            \
      F(VFMSUBADD132PD)                         \
      F(VFMSUBADD132PS)                         \
      F(VFMSUBADD213PD)                         \
      F(VFMSUBADD213PS)                         \
      F(VFMSUBADD231PD)                         \
      F(VFMSUBADD231PS)                         \
      F(VFMSUBADDPD)                            \
      F(VFMSUBADDPS)                            \
      F(VFMSUBPD)                               \
      F(VFMSUBPS)                               \
      F(VFMSUBSD)                               \
      F(VFMSUBSS)                               \
      F(VFNMADD132PD)                           \
      F(VFNMADD132PS)                           \
      F(VFNMADD132SD)                           \
      F(VFNMADD132SS)                           \
      F(VFNMADD213PD)                           \
      F(VFNMADD213PS)                           \
      F(VFNMADD213SD)                           \
      F(VFNMADD213SS)                           \
      F(VFNMADD231PD)                           \
      F(VFNMADD231PS)                           \
      F(VFNMADD231SD)                           \
      F(VFNMADD231SS)                           \
      F(VFNMADDPD)                              \
      F(VFNMADDPS)                              \
      F(VFNMADDSD)                              \
      F(VFNMADDSS)                              \
      F(VFNMSUB132PD)                           \
      F(VFNMSUB132PS)                           \
      F(VFNMSUB132SD)                           \
      F(VFNMSUB132SS)                           \
      F(VFNMSUB213PD)                           \
      F(VFNMSUB213PS)                           \
      F(VFNMSUB213SD)                           \
      F(VFNMSUB213SS)                           \
      F(VFNMSUB231PD)                           \
      F(VFNMSUB231PS)                           \
      F(VFNMSUB231SD)                           \
      F(VFNMSUB231SS)                           \
      F(VFNMSUBPD)                              \
      F(VFNMSUBPS)                              \
      F(VFNMSUBSD)                              \
      F(VFNMSUBSS)                              \
      F(VFRCZPD)                                \
      F(VFRCZPS)                                \
      F(VFRCZSD)                                \
      F(VFRCZSS)                                \
      F(VGATHERDPD)                             \
      F(VGATHERDPS)                             \
      F(VGATHERQPD)                             \
      F(VGATHERQPS)                             \
      F(VHADDPD)                                \
      F(VHADDPS)                                \
      F(VHSUBPD)                                \
      F(VHSUBPS)                                \
      F(VINSERTF128)                            \
      F(VINSERTI128)                            \
      F(VINSERTPS)                              \
      F(VLDDQU)                                 \
      F(VLDMXCSR)                               \
      F(VMASKMOVDQU)                            \
      F(VMASKMOVPD)                             \
      F(VMASKMOVPS)                             \
      F(VMAXPD)                                 \
      F(VMAXPS)                                 \
      F(VMAXSD)                                 \
      F(VMAXSS)                                 \
      F(VMCALL)                                 \
      F(VMCLEAR)                                \
      F(VMFUNC)                                 \
      F(VMINPD)                                 \
      F(VMINPS)                                 \
      F(VMINSD)                                 \
      F(VMINSS)                                 \
      F(VMLAUNCH)                               \
      F(VMLOAD)                                 \
      F(VMMCALL)                                \
      F(VMOVAPD)                                \
      F(VMOVAPS)                                \
      F(VMOVD)                                  \
      F(VMOVDDUP)                               \
      F(VMOVDQA)                                \
      F(VMOVDQU)                                \
      F(VMOVHLPS)                               \
      F(VMOVHPD)                                \
      F(VMOVHPS)                                \
      F(VMOVLHPS)                               \
      F(VMOVLPD)                                \
      F(VMOVLPS)                                \
      F(VMOVMSKPD)                              \
      F(VMOVMSKPS)                              \
      F(VMOVNTDQ)                               \
      F(VMOVNTDQA)                              \
      F(VMOVNTPD)                               \
      F(VMOVNTPS)                               \
      F(VMOVQ)                                  \
      F(VMOVSD)                                 \
      F(VMOVSHDUP)                              \
      F(VMOVSLDUP)                              \
      F(VMOVSS)                                 \
      F(VMOVUPD)                                \
      F(VMOVUPS)                                \
      F(VMPSADBW)                               \
      F(VMPTRLD)                                \
      F(VMPTRST)                                \
      F(VMREAD)                                 \
      F(VMRESUME)                               \
      F(VMRUN)                                  \
      F(VMSAVE)                                 \
      F(VMULPD)                                 \
      F(VMULPS)                                 \
      F(VMULSD)                                 \
      F(VMULSS)                                 \
      F(VMWRITE)                                \
      F(VMXOFF)                                 \
      F(VMXON)                                  \
      F(VORPD)                                  \
      F(VORPS)                                  \
      F(VPABSB)                                 \
      F(VPABSD)                                 \
      F(VPABSW)                                 \
      F(VPACKSSDW)                              \
      F(VPACKSSWB)                              \
      F(VPACKUSDW)                              \
      F(VPACKUSWB)                              \
      F(VPADDB)                                 \
      F(VPADDD)                                 \
      F(VPADDQ)                                 \
      F(VPADDSB)                                \
      F(VPADDSW)                                \
      F(VPADDUSB)                               \
      F(VPADDUSW)                               \
      F(VPADDW)                                 \
      F(VPALIGNR)                               \
      F(VPAND)                                  \
      F(VPANDN)                                 \
      F(VPAVGB)                                 \
      F(VPAVGW)                                 \
      F(VPBLENDD)                               \
      F(VPBLENDVB)                              \
      F(VPBLENDW)                               \
      F(VPBROADCASTB)                           \
      F(VPBROADCASTD)                           \
      F(VPBROADCASTQ)                           \
      F(VPBROADCASTW)                           \
      F(VPCLMULQDQ)                             \
      F(VPCMOV)                                 \
      F(VPCMPEQB)                               \
      F(VPCMPEQD)                               \
      F(VPCMPEQQ)                               \
      F(VPCMPEQW)                               \
      F(VPCMPESTRI)                             \
      F(VPCMPESTRM)                             \
      F(VPCMPGTB)                               \
      F(VPCMPGTD)                               \
      F(VPCMPGTQ)                               \
      F(VPCMPGTW)                               \
      F(VPCMPISTRI)                             \
      F(VPCMPISTRM)                             \
      F(VPCOMB)                                 \
      F(VPCOMD)                                 \
      F(VPCOMQ)                                 \
      F(VPCOMUB)                                \
      F(VPCOMUD)                                \
      F(VPCOMUQ)                                \
      F(VPCOMUW)                                \
      F(VPCOMW)                                 \
      F(VPERM2F128)                             \
      F(VPERM2I128)                             \
      F(VPERMD)                                 \
      F(VPERMILPD)                              \
      F(VPERMILPS)                              \
      F(VPERMPD)                                \
      F(VPERMPS)                                \
      F(VPERMQ)                                 \
      F(VPEXTRB)                                \
      F(VPEXTRD)                                \
      F(VPEXTRQ)                                \
      F(VPEXTRW)                                \
      F(VPGATHERDD)                             \
      F(VPGATHERDQ)                             \
      F(VPGATHERQD)                             \
      F(VPGATHERQQ)                             \
      F(VPHADDBD)                               \
      F(VPHADDBQ)                               \
      F(VPHADDBW)                               \
      F(VPHADDD)                                \
      F(VPHADDDQ)                               \
      F(VPHADDSW)                               \
      F(VPHADDUBD)                              \
      F(VPHADDUBQ)                              \
      F(VPHADDUBW)                              \
      F(VPHADDUDQ)                              \
      F(VPHADDUWD)                              \
      F(VPHADDUWQ)                              \
      F(VPHADDW)                                \
      F(VPHADDWD)                               \
      F(VPHADDWQ)                               \
      F(VPHMINPOSUW)                            \
      F(VPHSUBBW)                               \
      F(VPHSUBD)                                \
      F(VPHSUBDQ)                               \
      F(VPHSUBSW)                               \
      F(VPHSUBW)                                \
      F(VPHSUBWD)                               \
      F(VPINSRB)                                \
      F(VPINSRD)                                \
      F(VPINSRQ)                                \
      F(VPINSRW)                                \
      F(VPMACSDD)                               \
      F(VPMACSDQH)                              \
      F(VPMACSDQL)                              \
      F(VPMACSSDD)                              \
      F(VPMACSSDQH)                             \
      F(VPMACSSDQL)                             \
      F(VPMACSSWD)                              \
      F(VPMACSSWW)                              \
      F(VPMACSWD)                               \
      F(VPMACSWW)                               \
      F(VPMADCSSWD)                             \
      F(VPMADCSWD)                              \
      F(VPMADDUBSW)                             \
      F(VPMADDWD)                               \
      F(VPMASKMOVD)                             \
      F(VPMASKMOVQ)                             \
      F(VPMAXSB)                                \
      F(VPMAXSD)                                \
      F(VPMAXSW)                                \
      F(VPMAXUB)                                \
      F(VPMAXUD)                                \
      F(VPMAXUW)                                \
      F(VPMINSB)                                \
      F(VPMINSD)                                \
      F(VPMINSW)                                \
      F(VPMINUB)                                \
      F(VPMINUD)                                \
      F(VPMINUW)                                \
      F(VPMOVMSKB)                              \
      F(VPMOVSXBD)                              \
      F(VPMOVSXBQ)                              \
      F(VPMOVSXBW)                              \
      F(VPMOVSXDQ)                              \
      F(VPMOVSXWD)                              \
      F(VPMOVSXWQ)                              \
      F(VPMOVZXBD)                              \
      F(VPMOVZXBQ)                              \
      F(VPMOVZXBW)                              \
      F(VPMOVZXDQ)                              \
      F(VPMOVZXWD)                              \
      F(VPMOVZXWQ)                              \
      F(VPMULDQ)                                \
      F(VPMULHRSW)                              \
      F(VPMULHUW)                               \
      F(VPMULHW)                                \
      F(VPMULLD)                                \
      F(VPMULLW)                                \
      F(VPMULUDQ)                               \
      F(VPOR)                                   \
      F(VPPERM)                                 \
      F(VPROTB)                                 \
      F(VPROTD)                                 \
      F(VPROTQ)                                 \
      F(VPROTW)                                 \
      F(VPSADBW)                                \
      F(VPSHAB)                                 \
      F(VPSHAD)                                 \
      F(VPSHAQ)                                 \
      F(VPSHAW)                                 \
      F(VPSHLB)                                 \
      F(VPSHLD)                                 \
      F(VPSHLQ)                                 \
      F(VPSHLW)                                 \
      F(VPSHUFB)                                \
      F(VPSHUFD)                                \
      F(VPSHUFHW)                               \
      F(VPSHUFLW)                               \
      F(VPSIGNB)                                \
      F(VPSIGND)                                \
      F(VPSIGNW)                                \
      F(VPSLLD)                                 \
      F(VPSLLDQ)                                \
      F(VPSLLQ)                                 \
      F(VPSLLVD)                                \
      F(VPSLLVQ)                                \
      F(VPSLLW)                                 \
      F(VPSRAD)                                 \
      F(VPSRAVD)                                \
      F(VPSRAW)                                 \
      F(VPSRLD)                                 \
      F(VPSRLDQ)                                \
      F(VPSRLQ)                                 \
      F(VPSRLVD)                                \
      F(VPSRLVQ)                                \
      F(VPSRLW)                                 \
      F(VPSUBB)                                 \
      F(VPSUBD)                                 \
      F(VPSUBQ)                                 \
      F(VPSUBSB)                                \
      F(VPSUBSW)                                \
      F(VPSUBUSB)                               \
      F(VPSUBUSW)                               \
      F(VPSUBW)                                 \
      F(VPTEST)                                 \
      F(VPUNPCKHBW)                             \
      F(VPUNPCKHDQ)                             \
      F(VPUNPCKHQDQ)                            \
      F(VPUNPCKHWD)                             \
      F(VPUNPCKLBW)                             \
      F(VPUNPCKLDQ)                             \
      F(VPUNPCKLQDQ)                            \
      F(VPUNPCKLWD)                             \
      F(VPXOR)                                  \
      F(VRCPPS)                                 \
      F(VRCPSS)                                 \
      F(VROUNDPD)                               \
      F(VROUNDPS)                               \
      F(VROUNDSD)                               \
      F(VROUNDSS)                               \
      F(VRSQRTPS)                               \
      F(VRSQRTSS)                               \
      F(VSHUFPD)                                \
      F(VSHUFPS)                                \
      F(VSQRTPD)                                \
      F(VSQRTPS)                                \
      F(VSQRTSD)                                \
      F(VSQRTSS)                                \
      F(VSTMXCSR)                               \
      F(VSUBPD)                                 \
      F(VSUBPS)                                 \
      F(VSUBSD)                                 \
      F(VSUBSS)                                 \
      F(VTESTPD)                                \
      F(VTESTPS)                                \
      F(VUCOMISD)                               \
      F(VUCOMISS)                               \
      F(VUNPCKHPD)                              \
      F(VUNPCKHPS)                              \
      F(VUNPCKLPD)                              \
      F(VUNPCKLPS)                              \
      F(VXORPD)                                 \
      F(VXORPS)                                 \
      F(VZEROALL)                               \
      F(VZEROUPPER)                             \
      F(WBINVD)                                 \
      F(WRFSBASE)                               \
      F(WRGSBASE)                               \
      F(WRMSR)                                  \
      F(XABORT)                                 \
      F(XADD)                                   \
      F(XBEGIN)                                 \
      F(XCHG)                                   \
      F(XEND)                                   \
      F(XGETBV)                                 \
      F(XLAT)                                   \
      F(XOR)                                    \
      F(XORPD)                                  \
      F(XORPS)                                  \
      F(XRSTOR)                                 \
      F(XRSTOR64)                               \
      F(XSAVE)                                  \
      F(XSAVE64)                                \
      F(XSAVEOPT)                               \
      F(XSAVEOPT64)                             \
      F(XSETBV)                                 \
      F(XTEST)

#endif // __INTEL_XED_OPCODES__HPP
